<?php
namespace Ob;

Class Welcome extends Controller {
    
    function __construct()
    {           
        parent::__construct();
       
        // new Database\Db;
    }
    
    public function index()
    {        
        // new view\start();
        
        // view\set_var('variable', 'and generated by obullo.');

        // $user = new Model\Welcome\User();
        // $email = new Email\Email(false);
        
        log\me('debug', 'test');
        
        new i\start();
        
        i\post('');
        i\get('');

        vi\get('welcome', '', false);
    }
    
    function hmvc()
    {
        new Hmvc\request();

        $data = array();
        $data['response_a'] = request('welcome/test/1/2/3')->exec();
        $data['response_b'] = request('welcome/test/1/5/6')->exec();
        
        vi\get('hmvc', $data, false);
    }
    
    function test($arg1 = '', $arg2 = '', $arg3 = '')
    {
        echo '<pre>Response: '.$arg1 .' - '.$arg2. ' - '.$arg3.'</pre>';
    }
     
    function task($mode = '')
    {
        if(PHP_OS != 'Linux')
        {
            exit('Please run task functionality under the linux platforms.');
        }
        
        new task\start(); // Call the task helper
        
        echo "<font size='2'>";
        echo "You should run this command with none true or 'false' ";
        echo "argument when you go LIVE server ! .<br />.e.g. task_run('module/controller/method', false);";
        echo '<br />';
        echo url\anchor('welcome/task/help', 'Click Here to Help !');
        echo "<font>";
        
        if($mode == 'help')
        {
            $output = task\run('start/help', $output = true);  // use without true when you go live.
            echo '<pre>'.$output.'</pre>';
        }
        else
        {
            $output = task\run('start/index', $output = true); // use without true when you go live.
            echo '<pre>'.$output.'</pre>';
        }
    }
    
}

/* End of file start.php */
/* Location: .modules/welcome/controllers/welcome.php */