#!/bin/bash

PROJECT_DIR=${PWD}

## Learning the Shell
## http://linuxcommand.org/wss0090.php
if [ -z $1 ]; then
	echo 'Host name cannot be empty !';
	exit 1;
fi;

CONF=".conf";

echo "127.0.0.1	$1" >> /etc/hosts;
echo "<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        ServerName $1

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/$1

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
</VirtualHost>" > /etc/apache2/sites-available/$1$CONF;

sudo a2ensite $1;
sudo service apache2 restart;




