<?php

#######################################
##
##  DO NOT EDIT THIS FILE !
##
#######################################

// Please do not edit this file 
// Obm writes the package.json outputs here.

$packages = array(
    'name' => 'Obullo',
    'version' => '2.0',
    'db_layer' => 'Database_Pdo',
    'dependencies' => array(
        'acl'  => array('version' => '0.0.1', 'component' => 'library'),
        'auth'  => array('version' => '0.0.1', 'component' => 'library'),
        'agent'  => array('version' => '0.0.1', 'component' => 'library'),
        'bench' => array('version' => '0.0.1', 'component' => 'helper'),
        'cart' => array('version' =>  '0.0.1', 'component' => 'library'),
        'config' => array('version' =>  '0.0.1', 'component' => 'library'),
        'controller' => array('version' =>  '0.0.1', 'component' => 'library'),
        'cookie' => array('version' =>  '0.0.1', 'component' => 'helper'),
        'db' => array('version' => '0.0.1', 'component' => 'library'),
        'database_pdo' => array('version' => '0.0.1', 'component' => 'library'),
        'error' => array('version' => '0.0.1', 'component' => 'helper'),
        'email' => array('version' => '0.0.1', 'component' => 'library'),
        'encrypt' => array('version' => '0.0.1', 'component' => 'library'),
        'exception' => array('version' => '0.0.1', 'component' => 'library'),
        'form' => array('version' => '0.0.1', 'component' => 'helper'),
        'form_json' => array('version' => '0.0.1', 'component' => 'helper'),
        'ftp' => array('version' => '0.0.1', 'component' => 'library'),
        'html' => array('version' => '0.0.1', 'component' => 'helper'),
        'hmvc' => array('version' => '0.0.1', 'component' => 'library'),
        'i' => array('version' => '0.0.1', 'component' => 'helper'),
        'input' => array('version' => '0.0.1', 'component' => 'library'),
        'log' => array('version' => '0.0.1', 'component' => 'helper'),
        'locale' => array('version' => '0.0.1', 'component' => 'library'),
        'model' => array('version' => '0.0.1', 'component' => 'library'),
        'mongo_db' => array('version' => '0.0.1', 'component' => 'library'),
        'odm'  => array('version' => '0.0.1', 'component' => 'library'),
        'output'  => array('version' => '0.0.1', 'component' => 'library'),
        'pager'  => array('version' => '0.0.1', 'component' => 'library'),
        'pdo_mysql'  => array('version' => '0.0.1', 'component' => 'library'),
        'router' =>  array('version' => '0.0.1', 'component' => 'library'),
        'request' => array('version' => '0.0.1', 'component' => 'helper'),
        'security' => array('version' => '0.0.1', 'component' => 'library'), 
        'sess' => array('version' => '0.0.1', 'component' => 'helper'), 
        'sess_cookie' => array('version' => '0.0.1', 'component' => 'library'), 
        'string' => array('version' => '0.0.1', 'component' => 'helper'), 
        'task'  => array('version' => '0.0.1', 'component' => 'helper'),
        'validator' => array('version' => '0.0.1', 'component' => 'library'),
        'uri' => array('version' => '0.0.1', 'component' => 'library'),
        'url' => array('version' => '0.0.1', 'component' => 'helper'),
        'utf8' => array('version' => '0.0.1', 'component' => 'library'),
        'vi' => array('version' => '0.0.1', 'component' => 'helper'),
        'view' => array('version' => '0.0.1', 'component' => 'library'),
    )
  );

##  DO NOT EDIT THIS FILE

// Please do not edit this file 
// Obm writes the package.json outputs here.