<?php
##  DO NOT EDIT THIS FILE
#
// Please do not edit this file 
// Obm writes the package.json outputs here.

$packages = array(
    'name' => 'Obullo',
    'version' => '2.0',
    'db_class' => 'Database_PDO',
    'dependencies' => array(
        'auth'  => array('version' => '0.0.1', 'component' => 'library'),
        'benchmark' => array('version' => '0.0.1', 'component' => 'library'),
        'config' => array( 'repo' => 'https://github.com/eguvenc/config.git', 'version' =>  '0.0.1', 'component' => 'library'),
        'database_pdo' => array('version' => '0.0.1', 'component' => 'library'),
        'error' => array('version' => '0.0.1', 'component' => 'helper'),
        'exceptions' => array('version' => '0.0.1', 'component' => 'library'),
        'form' => array('version' => '0.0.1', 'component' => 'helper'),
        'form_json' => array('version' => '0.0.1', 'component' => 'helper'),
        'html' => array('version' => '0.0.1', 'component' => 'helper'),
        'input' => array('version' => '0.0.1', 'component' => 'library'),
        'log' => array('version' => '0.0.1', 'component' => 'helper'),
        'locale' => array('version' => '0.0.1', 'component' => 'library'),
        'output'  => array('version' => '0.0.1', 'component' => 'library'),
        'pdo_mysql'  => array('version' => '0.0.1', 'component' => 'library'),
        'router' =>  array('version' => '0.0.1', 'component' => 'library'),
        'request' => array('version' => '0.0.1', 'component' => 'helper'),
        'security' => array('version' => '0.0.1', 'component' => 'helper'), 
        'session' => array('version' => '0.0.1', 'component' => 'helper'), 
        'string' => array('version' => '0.0.1', 'component' => 'helper'), 
        'task'  => array('version' => '0.0.1', 'component' => 'helper'),
        'uri' => array('version' => '0.0.1', 'component' => 'library'),
        'url' => array('version' => '0.0.1', 'component' => 'helper'),
        'view' => array('version' => '0.0.1', 'component' => 'helper'),
    )
  );

##  DO NOT EDIT THIS FILE

// Please do not edit this file 
// Obm writes the package.json outputs here.