<?php
/*
|--------------------------------------------------------------------------
| General Config
|--------------------------------------------------------------------------
| This file specifies the global configurations of your application.
*/
return array(
                          
    'error' => [
        'debug' => true,            // Friendly debugging feature disable it in "production" environment.
    ],                              // If log enabled all errors go to log data otherwise framework use php native errors.

    'url' => [
        'webhost'  => 'framework',  // Your web host name default "localhost" should be "example.com" in production config.
        'baseurl'  => '/',          // Base Url "/" URL of your framework root, generally a '/' trailing slash. 
        'assets'   => [
            'url' => '/',           // Assets url of your framework generally a '/' you may want to change it with your "cdn" provider.
            'folder' => '/assets/', // Assets folder
        ],    
        'rewrite' => [
            'indexPage'    => '',  // Typically this will be your index.php file, If mod_rewrite enabled is should be blank.
            'suffix'  => '',       // Allows you to add a suffix to all URLs generated by Framework.
        ]
    ],

    'log' => [
        'enabled' => true,         // Enable / Disable logging ( If log disabled run php native errors )
    ],

    'debugger' => [
        'enabled' => false,
        'socket'  => 'ws://127.0.0.1:9000'
    ],

    'uri' => [
        'protocol' => 'REQUEST_URI',   // Options: REQUEST_URI, QUERY_STRING, PATH_INFO Example : http://example.com/login?param=1&param2=yes
        'sanitizer' => true,           // Remove all characters except letters, digits and $-_.+!*'(],{}|\\^~[]`<>#%";/?:@&=.
        'queryStrings' => true,        // Allows query string based URLs: example.com/directory/controller?who=me&what=something&where=here
        'extensions' => ['.json','.xml','.html'],   // Allows extension based URLs: example.com/api/get/users.json
    ],

    'locale' => [
        'timezone' => 'gmt',      // This pref tells the system whether to use your server's "local" time as the master now reference, or convert it to "gmt".
        'charset'  => 'UTF-8',    // This determines which character set is used by default.
        'date' => [
            'php_date_default_timezone' => 'Europe/London',  // Sets timezone using php date_default_timezone_set(]; function.
            'format' => 'H:i:s d:m:Y'
        ]
     ],

    'annotations' => [
        'enabled' => true,   // Enable / Disable "annotations".
    ],

    'layer' => [
        'cache' => false     // Enable / Disable global cache feature for Layer package.
    ],

    'cookie' => [ 
        'domain' => $c['env']['COOKIE_DOMAIN.null'],    // Set to .your-domain.com for site-wide cookies
        'path'   => '/',                                // Typically will be a forward slash
        'secure' => false,                              // Cookies will only be set if a secure HTTPS connection exists.
        'httpOnly' => false,                            // When true the cookie will be made accessible only through the HTTP protocol
        'expire' => 604800,                             // 1 week - Cookie expire time.
        'prefix' => '',                                 // Set a prefix if you need to avoid collisions
    ],

    'proxy' => [          // Reverse Proxy IPs , If your server is behind a reverse proxy, you must whitelist the proxy IP
        'ips' => '',      // addresses from which the Application should trust the HTTP_X_FORWARDED_FOR
    ],                    // header in order to properly identify the visitor's IP address.
                          // Comma-delimited, e.g. '10.0.1.200,10.0.1.201'

    'output' => [
        'compress' => false,  // Enables Gzip output compression for faster page loads.  When enabled,
    ],                        // the Response class will test whether your server supports Gzip.
                              // Even if it does, however, not all browsers support compression
                              // so enable only if you are reasonably sure your visitors can handle it
);

/* End of file config.php */
/* Location: .app/config/env/local/config.php */