<?php
/*
|--------------------------------------------------------------------------
| Application "production" environment
|--------------------------------------------------------------------------
|
| IMPORTANT :
|
| You don't need copy / paste all of the config.php keys
| just get configuration key differences from local/config.php and paste here.
|
*/

return array(
                    
    'error' => array(
        'debug' => false,       // Friendly debugging feature should be "Disabled"" in "PRODUCTION" environment.
        'reporting' => false,   // Turn on it if you want catch "unusual hidden errors", should be "Disabled"" in "PRODUCTION".
    ),

    'log' =>   array(
        'control' => array(
            'enabled' => true,
            'output'  => false,
    ),

    'url' => array(
        'host'   => 'framework', // Your Virtual host name default "localhost" should be "example.com" in production config.
        'base'   => '/',         // Base Url "/" URL of your framework root, generally a '/' trailing slash. 
        'assets' => '/assets/',  // Assets Url of your framework generally a '/assets/' you may want to change it with your "cdn" provider.
        'rewrite' => array(
            'indexPage' => '',   // Typically this will be your index.php file, If mod_rewrite enabled is should be blank.
            'suffix'    => '',   // Allows you to add a suffix to all URLs generated by Framework.
        )
    ),
    
    // 'database' => config('database.php'), // Databases
    // 'session' => config('session.php'),   // Sessions
    // 'nosql' => config('nosql.php'),       // NoSQL Databases
    // 'mail' => config('mail.php'),         // Mail
    // 'cache' => config('cache.php'),       // Cache
    // 'queue' => config('queue.php'),       // Queue

);

/* End of file config.php */
/* Location: .app/env/local/config.php */